#import dirichlet_conrey
#import permutation_alg
from dirichlet_conrey import  DirichletGroup_conrey,DirichletCharacter_conrey
from permutation_alg import MyPermutation,MyPermutationIterator,CycleCombinationIterator
